# Generated by Django 5.0 on 2023-12-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='labproduct',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
