# Generated by Django 5.0 on 2024-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
